import type { Metadata } from "next";
// 1. Import the desired fonts from the next/font/google library.
import { Abel, Cormorant_Garamond, Acme } from "next/font/google";
// Import the global Header component, which will appear on every page.
import Header from "@/components/common/Header/Header"; 
// Import the global stylesheet.
import "./globals.css";

// 2. Configure each font.
// This downloads the font at build time and hosts it with your static assets.
const abel = Abel({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abel", // Assigns the font to a CSS variable for easy use in stylesheets.
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-cormorant",
});

const acme = Acme({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-acme",
});

// 3. Define metadata for the application (e.g., for the browser tab title).
export const metadata: Metadata = {
  title: "Cosmic Soul",
  description: "Generated by create next app",
};

// This is the root layout component that wraps every page in your application.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 4. Apply the font classes and variables to the body tag. */}
      {/* - `abel.className` sets Abel as the default font for the entire site. */}
      {/* - The `.variable` properties make the other fonts available as CSS variables. */}
      <body className={`${abel.className} ${cormorant.variable} ${acme.variable}`}>
        <Header />
        <main className="main-content">{children}</main>
      </body>
    </html>
  );
}