import type { Metadata } from "next";
import { Abel, Cormorant_Garamond, Acme } from "next/font/google";
import Header from "@/components/common/Header/Header";
import "./globals.css";

const abel = Abel({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abel",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-cormorant",
});

const acme = Acme({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-acme",
});

export const metadata = {
  title: "Cosmic Soul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abel.className} ${cormorant.variable} ${acme.variable}`}>
        <Header />
        {/* Add a className to the main tag */}
        <main className="main-content">{children}</main>
      </body>
    </html>
  );
}